package common;

import static org.junit.Assert.*;

import org.junit.Test;

import common.Library;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'm-hiki' at '16/05/27 21:07' with Gradle 2.13
 *
 * @author m-hiki, @date 16/05/27 21:07
 */

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
