/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm-hiki' at '16/05/27 21:07' with Gradle 2.13
 *
 * @author m-hiki, @date 16/05/27 21:07
 */

package common;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
