spring:
  profiles: dev

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:dbname
    username: schemaname
    password: password
    maxActive: 0
    maxIdle: 5
    maxWait: 30000
    initialSize: 5
  thymeleaf:
     cache: false

