spring:
  profiles: stg_real
  application:
    name: spring-boot-sample
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:dbname
    username: schemaname
    password: password
    maxActive: 0
    maxIdle: 5
    maxWait: 30000
    initialSize: 5
  thymeleaf:
     cache:false

#  mybatis:
    #mapper-locations:
    #    - classpath*:front/repository/mapper/*.xml"
#    configLocation:"mybatis-config.xml"


